#!/bin/bash
# ************************************************************************************
#   Copyright (C) 2022 MariaDB Corporation AB
#   
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Library General Public
#   License as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#   
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Library General Public License for more details.
#   
#   You should have received a copy of the GNU Library General Public
#   License along with this library; if not see <http://www.gnu.org/licenses>
#   or write to the Free Software Foundation, Inc., 
#   51 Franklin St., Fifth Floor, Boston, MA 02110, USA
# *************************************************************************************/

if [ $2 ]; then
  target=$2
  case "$target" in
  */)
    LINKHEADERS=1
    ;;
  *)
    target="${target}/"
    ;;
  esac
fi

set -a
#instinidir="$(dirname -- "$ODBCINSTINI")"

if [ ! -z "$LINKHEADERS" ]; then
 ln -s /Applications/MariaDB/MariaDB-Connector-Cpp/libmariadbcpp.dylib /usr/local/lib/libmariadbcpp.dylib
 ln -s /Applications/MariaDB/MariaDB-Connector-Cpp/include/mariadb /usr/local/include/mariadb
fi

exit 0
